spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dang-diary-database.cfq6mukg6rp1.ap-northeast-2.rds.amazonaws.com:3306/dang_diary?serverTimezone=UTC
    username: root
    password: apfhdz12
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

image:
  path: file:/home/ec2-user/DangDiaryServer/src/main/webapp/upload/
  save:
    path: /home/ec2-user/DangDiaryServer/src/main/webapp/upload/

domain: 13.209.13.206
