spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dang_diary?serverTimezone=UTC
    username: root
    password: 1234
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        hbm2ddl.auto: update

image:
  path: file:/Users/ung/Documents/Spring/DangDiaryServer/src/main/webapp/upload/
  save:
    path: /Users/ung/Documents/Spring/DangDiaryServer/src/main/webapp/upload/

domain: localhost

springdoc:
  swagger-ui:
    path: /dangdiary/swagger.html
    groups-order: DESC # path, query, body, response 순으로 출력
    tags-sorter: alpha # 태그를 알파벳 순으로 정렬
    operations-sorter: method  # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능


server:
  max-http-request-header-size: 32768

logging:
  level:
    root: INFO
    com.dang diary: DEBUG